refactoring of auth token
multiversx/mx-ledger-nano pull request #73
Opened 2023-02-08 14:02 UTC by bogdan-rosianu

2023-02-17 10:17 UTC, mariusmihaic commented on tests/test_elrond.py
> +            if backend.firmware.device.startswith("nano"):
Does this take care of every device? E.g.: nanos/nanox ?

2023-02-17 11:09 UTC, bogdan-rosianu commented on src/constants.h
> +#define MAX_AUTH_TOKEN_TTL_LEN      40
just some magic numbers I've found during testing

2023-02-17 13:00 UTC, bogdan-rosianu commented on src/parse_tx.c
> +    // gas_unit_for_move_balance) * gas_price_modifier * gas_limit. the difference
done

2023-02-17 13:06 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    bG9jYWxob3N0.f68177510756edce45eca84b94544a6eacdfa36e69dfd3b8f24c4010d1990751.300.eyJ0aW1lc3RhbXAiOjE2NzM5NzIyNDR9
done

2023-02-17 13:08 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +                token_auth_context.auth_body[strlen(token_auth_context.auth_body) + 1] = '\0';
replaced with continue

2023-02-17 13:08 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +                if (strlen(token_auth_context.auth_body) > 100) {
added

2023-02-17 13:08 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +                if (strlen(token_auth_context.auth_body) > 10) {
added

2023-02-17 13:09 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +                    break;
no, it's fine, since on the `compute_token_display` I perform the following 2 checks:
1. if the hostname is empty, early exit - display the token as it is
2. if the ttl is empty, then display `N/A time` instead

2023-02-17 13:16 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +void handle_auth_token_data(uint8_t const *data_buffer, uint8_t data_length) {
split into more functions (one for extracting hostname and one for extracting the ttl)

2023-02-17 13:19 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +        memmove(token_auth_context.token, display, 100);
the trim functionality was not needed at this point, since all the components that compose the display are less than 100 characters. Also, refactored the compute_token_display to take the max size of 100 into account

2023-02-17 13:22 UTC, bogdan-rosianu commented on src/utils.c
> +    }
yup, very good suggestion. applied

2023-02-17 13:29 UTC, bogdan-rosianu commented on src/utils.c
> +int myAtoi(const char* str) {
I didn't add that many checks, but guarded the function via:
1. check that each character is a digit
2. the encoded ttl len is set to 10 (including `\0`), while MAX INT has 10 characters. therefore, overflows cannot appear

2023-02-17 13:29 UTC, bogdan-rosianu commented on src/utils.c
> +    for (int i = 0; str[i] != '\0'; ++i) res = res * 10 + str[i] - '0';
yup, added

2023-02-17 13:30 UTC, bogdan-rosianu commented on src/utils.c
> +        current_temp_output_index += 2;
`"h "` has 2 characters
`"min "` has 4 characters

2023-02-17 13:32 UTC, bogdan-rosianu commented on src/utils.c
> +        current_temp_output_index += 4;
there would have been too many variables passed around, such as the `current_temp_output_index`. the logic is pretty simple, just that it is written in many lines of code. Not a strong opinion, tho

2023-02-17 13:33 UTC, bogdan-rosianu commented on src/utils.c
> +        return -1;
added

2023-02-17 13:37 UTC, bogdan-rosianu commented on src/utils.c
> +    // base64decode function can return '?' characters. we'll remove them
If I don't add the padding, the conversion wouldn't work. Take for example the hostname `t` which is `dA==` base64 encoded. the token received won't have the padding so it will be `dA`. the first line of the `base64decode` function is:
```
for (size_t i = 0; i < len / 4; i++) {
```
meaning that it won't work for strings shorter than 4 characters (`dA` for example).

Of course, `base64decode` function could deserve refactoring. However, I do not think it is in the scope of this PR, since the implications of the change are pretty big.

2023-02-20 08:33 UTC, bogdan-rosianu commented on tests/test_elrond.py
> +            if backend.firmware.device.startswith("nano"):
yes, it will trigger the running of tests on each device

2023-02-20 08:34 UTC, bogdan-rosianu commented on src/utils.c
> +    display[12 + strlen(hostname_display) + 5 + strlen(ttl_display)] = '\0';
done

2023-02-20 08:35 UTC, bogdan-rosianu commented on src/utils.c
> +        int_to_char_array(s, seconds_char_arr, 10);
since by parsing the seconds number and division, we can only have valid inputs for the `int_to_char_array`, I don't think additional checks will help. I mean they won't disturb, but won't help

2023-02-20 16:27 UTC, mariusmihaic commented on src/utils.c
> +        output[8] = '\0';
Please add const for `8`

2023-02-20 16:27 UTC, mariusmihaic commented on src/utils.c
> +        current_temp_output_index += 4;
Yes, it would've been a bit trickier with sending all those params, but easier to read at caller level, as now you need to be extra careful for each h/m/s that the indexes are correct instead of reading the functionality from only one func

If it really is such an overhead to create a func from it, you can leave it as it is

2023-02-20 16:27 UTC, mariusmihaic commented on src/utils.c
> +    // base64decode function can return '?' characters. we'll remove them
Agree.
Can leave it as a future task/todo

2023-02-20 16:27 UTC, mariusmihaic commented on src/utils.c
> +    for_token[5] = '\0';
And for authorizing above, could we use one line, like:
https://www.tutorialspoint.com/cprogramming/c_strings.htm ?

2023-02-20 16:27 UTC, mariusmihaic commented on src/utils.c
> +    if (current_len > max_display_length) {
Instead of adding new char* to the display and checking after every append that the `max_display_length` has been reached, we could compute beforehand what is the `whole_length` and do only one if, instead of 4

2023-02-20 16:27 UTC, mariusmihaic commented on tests/test_elrond.py
> +    def test_sign_msg_auth_token_too_long_payload(self, backend, navigator, test_name):
Not sure if it's ok to ignore a too long payload. Could this also be a security issue?

2023-02-22 10:21 UTC, bogdan-rosianu commented on src/parse_tx.c
> +    // gas_unit_for_move_balance) * gas_price_modifier * gas_limit. the difference
done

2023-02-22 10:22 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    char auth_hostname[100];
outdated comment

2023-02-22 10:22 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    int ret_code = compute_token_display(token_auth_context.auth_hostname,
done

2023-02-22 10:27 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +        if (display_len > 100) {
the idea for this release is: if the new data can be fetched, so be it. if not, display the token just as before. In this case, `token_auth_context.token` already contains the token in plain text

2023-02-22 10:28 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +            display[display_len - 1] = '.';
outdated comment

2023-02-22 11:31 UTC, bogdan-rosianu commented on src/parse_tx.c
> +    // gas_unit_for_move_balance) * gas_price_modifier * gas_limit. The difference
done

2023-02-22 11:36 UTC, bogdan-rosianu commented on src/utils.c
> +        int hostname_length = strlen(hostname_display);
there is this check before decoding base64:
```
 int origin_max_length = strlen(encoded_origin);
    if (origin_max_length > MAX_AUTH_TOKEN_ORIGIN_LEN) {
        origin_max_length = MAX_AUTH_TOKEN_ORIGIN_LEN;
    }
```
perhaps outdated comment?

2023-02-22 11:44 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
>  static token_auth_context_t token_auth_context;
reset them for each call

2023-02-22 11:45 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    memmove(token_auth_context.auth_origin,
handled the reset

2023-02-22 11:45 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    memmove(token_auth_context.auth_ttl,
handled the reset

2023-02-22 11:47 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +void extract_ttl() {
done

2023-02-22 11:49 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +            if (strlen(token_auth_context.auth_token_buffer) >= AUTH_TOKEN_ENCODED_ORIGIN_MAX_LEN) {
done

2023-02-22 11:51 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +            token_auth_context.auth_token_buffer[strlen(token_auth_context.auth_token_buffer) + 1] =
extracted variable

2023-02-22 11:51 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    int ret_code = compute_token_display(token_auth_context.auth_origin,
yes

2023-02-22 11:58 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +        memmove(token_auth_context.token, display, strlen(display));
you're right. changed the `token_auth_context.token` to have the size `AUTH_TOKEN_DISPLAY_MAX_LEN`

2023-02-22 12:25 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +            if (token_auth_context.dot_count == 1) {
done

2023-02-22 16:41 UTC, AdoAdoAdo commented on src/utils.c
> +        for (int j = 0; j < padding_count; j++) {
not sure I understood here the intention
could you add a simple example?

for a padding_count = 3, you would add 3 times `=` at the end? 
shouldn't you add (4-padding_count) times `=` ?

2023-02-23 10:18 UTC, bogdan-rosianu commented on src/utils.c
> +    for (int i = 0; str[i] != '\0'; ++i) {
done

2023-02-23 13:17 UTC, bogdan-rosianu commented on src/utils.c
> +    char digits[max_size];
done. as discussed, added a const for the max num of digits of an integer. regarding L83 ( `result[current_result_index] = '\0';` ) it is safe, since we have the `if (current_digit_index + 1 > max_size) {` check

2023-02-23 13:22 UTC, bogdan-rosianu commented on src/utils.c
> +        output[8] = '\0';
added check

2023-02-23 13:22 UTC, bogdan-rosianu commented on src/utils.c
> +        memmove(result, "N/A", 3);
added

2023-02-23 14:07 UTC, bogdan-rosianu commented on src/utils.c
> +        char hours_char_arr[10];
done

2023-02-23 14:36 UTC, bogdan-rosianu commented on src/utils.c
> +    authorizing[12] = '\0';
refactored as suggested

2023-02-23 14:36 UTC, bogdan-rosianu commented on src/utils.c
> +    if (current_len > max_display_length) {
refactored as suggested

2023-02-23 15:13 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +                    break;
after internal discussions, we agreed that with this release, we'll only display the new data, if possible. on the next release, we won't allow tokens that don't follow our pattern

2023-02-23 15:13 UTC, bogdan-rosianu commented on src/utils.c
> +    }
yup, reverted

2023-02-23 15:13 UTC, bogdan-rosianu commented on src/utils.c
> +        current_temp_output_index += 4;
done

2023-02-23 15:13 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +            token_auth_context.auth_token_buffer[strlen(token_auth_context.auth_token_buffer) + 1] =
refactored the area

2023-02-23 15:14 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    if (ret_code != AUTH_TOKEN_INVALID_RET_CODE) {
added one more possible ret code

2023-02-23 15:14 UTC, bogdan-rosianu commented on src/utils.c
> +        output[8] = '\0';
refactored

2023-02-23 15:14 UTC, bogdan-rosianu commented on src/utils.c
> +    for_token[5] = '\0';
refactored the area

2023-02-23 15:14 UTC, bogdan-rosianu commented on src/utils.c
> +    if (current_len > max_display_length) {
refactored

2023-02-23 15:15 UTC, bogdan-rosianu commented on tests/test_elrond.py
> +    def test_sign_msg_auth_token_too_long_payload(self, backend, navigator, test_name):
for this version, for backward compatiblity reasons, we'll allow old tokens as well. starting with the next versions, we'll only allow tokens that follow our pattern

2023-02-23 15:19 UTC, bogdan-rosianu commented on src/utils.c
> +        for (int j = 0; j < padding_count; j++) {
good catch. refactored to use `padding_count` as `4 - mod_four`

2023-03-01 09:53 UTC, mariusmihaic reviewed
Good job with the refactor, code looking better :+1: . Left some minor final comments

2023-03-01 09:53 UTC, mariusmihaic commented on src/sign_msg_auth_token.c
> +    if (ret_code != AUTH_TOKEN_INVALID_RET_CODE) {
Still not ok.
Everytime you add one more ret code, you need another if here. Should only `memmove(token_auth_context.token, display, strlen(display));` when return code is `OK`

2023-03-01 09:53 UTC, mariusmihaic commented on src/utils.c
> +    if (*index > max_size || (int) (strlen(source) + *index) > (int) (max_size)) {
Second condition includes the first one; this could be simplified to just `(int) (strlen(source) + *index) > (int) (max_size)`
Also, func description is usually placed outside (above func), not inside

2023-03-01 09:53 UTC, mariusmihaic commented on src/utils.c
> +       34 sec."; 12345 -> "3h 25min 45 sec.". If more than 24h, will display accordingly
What does accordingly mean in this case? can you give an example?

2023-03-01 09:53 UTC, mariusmihaic commented on src/utils.c
> +        dest[len_src] = 0;
0 or `\0` ?

2023-03-01 09:53 UTC, mariusmihaic commented on src/utils.c
> +    return (allowed_len - truncate_str_len) / 2;
Tricky here if `allowed_len - truncate_str_len` is negative, you will then use a negative index

2023-03-01 09:53 UTC, mariusmihaic commented on src/utils.c
> +    const int truncate_str_len = sizeof(truncate_replacement) - 1;
These 2 lines can be moved inside else

2023-03-01 09:53 UTC, mariusmihaic commented on src/utils.c
> +    int num_elements = sizeof(elements) / sizeof(char*);
I think you've used this before somwhere; could've extracted in a `#DEFINE macro`

2023-03-01 09:53 UTC, mariusmihaic commented on src/utils.c
> +        }
I would've computed this before the `for` and only check once. Also, instead of `if not <`, i would replace it with `if >`

2023-03-01 10:20 UTC, AdoAdoAdo commented on src/utils.c
> +        dest[len_src] = 0;
'\0' ascii value is 0, so these are the same.

2023-03-02 15:15 UTC, AdoAdoAdo requested changes

2023-03-02 15:15 UTC, AdoAdoAdo commented on src/utils.c
> +        char hours_char_arr[max_int_char_array_len];
these seem like the same operations done for hours, minutes and seconds
could you create a function and call it?
``` C
void append_time(char *output, int max_size, int value, const char* tag);
```

then call it
e.g:
``` C
append_time(temp_output, max_size, h, "h ");
append_time(temp_output, max_size, m, "m ");
append_time(temp_output, max_size, s, "s ");

2023-03-02 15:27 UTC, bogdan-rosianu commented on src/utils.c
> +       34 sec."; 12345 -> "3h 25min 45 sec.". If more than 24h, will display accordingly
ok

2023-03-02 15:29 UTC, bogdan-rosianu commented on src/utils.c
> +    return (allowed_len - truncate_str_len) / 2;
even if this is not possible in the current implementation, returned `0` if the result is negative

2023-03-02 15:29 UTC, bogdan-rosianu commented on src/utils.c
> +    const int truncate_str_len = sizeof(truncate_replacement) - 1;
right. done

2023-03-02 15:32 UTC, bogdan-rosianu commented on src/utils.c
> +        }
done

2023-03-02 15:36 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +        memset(destination, 0, sizeof(*destination));
good catch, passe the sizes as parameters

2023-03-02 15:37 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    memset(buffer, 0, sizeof(*buffer));
fixed

2023-03-02 15:42 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +                                       AUTH_TOKEN_ENCODED_TTL_MAX_LEN);
renamed

2023-03-02 15:42 UTC, bogdan-rosianu commented on src/utils.c
> +    if (current_digit_index + 1 > max_size) {
done

2023-03-02 15:44 UTC, bogdan-rosianu commented on src/utils.c
> +    result[current_result_index] = '\0';
done

2023-03-02 15:44 UTC, bogdan-rosianu commented on src/utils.c
> +    /*
done

2023-03-02 15:46 UTC, bogdan-rosianu commented on src/utils.c
> +    char decoded_origin_buffer[AUTH_TOKEN_ENCODED_ORIGIN_MAX_LEN + 1];
done

2023-03-03 12:17 UTC, bogdan-rosianu commented on src/utils.c
> +    char encoded_origin[received_origin_len +
refactored

2023-03-03 12:18 UTC, bogdan-rosianu commented on src/utils.c
> +    int encoded_origin_max_length = strlen(encoded_origin);
removed (but not due to the suggested refactoring)

2023-03-03 12:19 UTC, bogdan-rosianu commented on src/utils.c
> +        memmove(ttl_display, "N/A time", 8);
done

2023-03-03 14:57 UTC, bogdan-rosianu commented on src/utils.c
> +        char hours_char_arr[max_int_char_array_len];
`append_time` would require the `current_temp_output_index` as well. therefore, this int parameter would be passed the second time a as pointer to a function, just for the sake of refactoring. not having a strong opinion, tho

2023-03-06 16:00 UTC, AdoAdoAdo commented on src/utils.c
>                            size_t max_display_length) {
can you rename here parameter to max_display_size?

2023-03-06 16:00 UTC, AdoAdoAdo commented on src/utils.c
> +        if (final_string_index + strlen(elements[i]) >= max_display_length) {
also here max_display_length -> max_display_size

2023-03-06 16:39 UTC, AdoAdoAdo commented on src/utils.c
> +        char hours_char_arr[max_int_char_array_len];
you only need to pass also reference to the index
```C
void append_time(char *output, char * index, int max_size, int value, const char* tag);
```
then call it
``` C
append_time(temp_output, &current_index, max_size, h, "h ");
append_time(temp_output, &current_index, max_size, m, "m ");
append_time(temp_output, &current_index, max_size, s, "s ");
```

2023-03-06 16:45 UTC, AdoAdoAdo commented on src/utils.c
> +    encoded_origin[encoded_origin_size] = '\0';
encoded_origin_size here could be an invalid index as you compute it as min between the received len and the max allowed size.
First one doesn't include the string terminator char, the second one does, but the size in that case is not a valid index.

let's discuss how to change, as I think there are other issues here.

2023-03-07 09:20 UTC, bogdan-rosianu commented on src/utils.c
> +        char hours_char_arr[max_int_char_array_len];
ok, refactored

2023-03-07 09:23 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +        memset(destination, 0, destination_size);
fixed

2023-03-07 09:24 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +                            int max_size) {
done

2023-03-07 09:25 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
>                                           AUTH_TOKEN_DISPLAY_MAX_LEN);
done

2023-03-07 09:29 UTC, bogdan-rosianu commented on src/utils.c
> -    */
renamed

2023-03-07 10:38 UTC, bogdan-rosianu commented on src/utils.c
> +    if ((int) (strlen(source) + *index) > (int) (max_size)) {
right. fixed

2023-03-07 10:39 UTC, bogdan-rosianu commented on src/utils.c
>                            size_t max_display_length) {
renamed

2023-03-07 10:39 UTC, bogdan-rosianu commented on src/utils.c
> +        if (final_string_index + strlen(elements[i]) >= max_display_length) {
done

2023-03-07 14:35 UTC, mariusmihaic commented on src/utils.c
> +            result[0] = '0';
Can it happen that we access `result` at an index out of bounds?

2023-03-07 14:37 UTC, mariusmihaic submitted a review, later dismissed

2023-03-08 08:09 UTC, AdoAdoAdo commented on src/utils.c
>      if (h > 0) {
you can move the check in the append_time function as well

2023-03-08 14:03 UTC, bogdan-rosianu commented on src/utils.c
> +            result[0] = '0';
since it is guarded by the `max_size` variable,  no

2023-03-08 14:21 UTC, bogdan-rosianu commented on src/utils.c
> +    encoded_origin[encoded_origin_size] = '\0';
refactored

2023-03-08 14:44 UTC, mariusmihaic submitted a review, later dismissed

2023-03-08 14:44 UTC, mariusmihaic commented on src/utils.c
> +        encoded_origin[encoded_origin_size - 1 + padding_count] = '\0';
Just a preference here, since I don't like that much following where this `-1` came from.

You could've declared an extra variable like this:
- `encoded_origin_len = encoded_origin_size-1`

Therefore, you would've used them here like this:
- `encoded_origin[encoded_origin_len + j] = '=';`
- `encoded_origin[encoded_origin_len + padding_count] = '\0';`

2023-03-08 14:50 UTC, bogdan-rosianu commented on src/utils.c
> +        encoded_origin[encoded_origin_size - 1 + padding_count] = '\0';
done

2023-03-08 15:13 UTC, mariusmihaic approved these changes

2023-03-08 15:51 UTC, AdoAdoAdo approved these changes

2023-03-09 09:04 UTC, merged