added guardians support
multiversx/mx-ledger-nano pull request #77
Opened 2023-04-06 13:22 UTC by bogdan-rosianu

Added Guardians support:
- accept `options` field to be higher than `1`
- accept `guardian` field
- display `Guardian` field when signing guarded transactions
- fixed linter issues raised by the new libs
- added tests for the new scenarios

2023-04-13 07:53 UTC, sstanculeanu commented on src/utils.c
> +    const int max_size = MAX_INT_NUM_DIGITS + 1;
```suggestion
    const int max_size = MAX_INT_NUM_DIGITS + 1;
    char buffer[max_size];
```

2023-04-13 08:05 UTC, bogdan-rosianu commented on src/utils.c
> +    const int max_size = MAX_INT_NUM_DIGITS + 1;
not applicable. I've tries this but I get this linter issue:
```
src/utils.c:140:17: warning: variable length array used [-Wvla]
    char buffer[max_size];

```

2023-04-13 08:25 UTC, sstanculeanu submitted a review, later dismissed

2023-04-18 12:31 UTC, AdoAdoAdo requested changes

2023-04-18 13:36 UTC, bogdan-rosianu commented on src/parse_tx.c
> +        memmove(ticker, TICKER_TESTNET, strlen(TICKER_TESTNET) + 1);
it was a linter issue. refactored

2023-04-18 13:41 UTC, bogdan-rosianu commented on src/utils.c
> +    char temp_output[MAX_AUTH_TOKEN_TTL_SIZE];
done

2023-04-18 14:04 UTC, bogdan-rosianu commented on src/sign_tx_hash.c
> +        if (strlen(tx_context.guardian) > 0) {
done

2023-04-18 14:05 UTC, bogdan-rosianu commented on tests/test_multiversx.py
> +            if backend.firmware.device.startswith("nano"):
the `with` blocks are not the same. They have different expected messages and different number of actions before asserting something

2023-04-19 08:28 UTC, sstanculeanu approved these changes

2023-04-19 08:28 UTC, merged